# See reference docs at
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      # https://github.com/golangci/golangci-lint-action
      - name: Lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          # There are a few existing lint errors; remove issues-exit-code
          # flag when resolved.
          args: --skip-dirs=cmd/playground --issues-exit-code=0
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
